### ISSUE TITLE
ATOMRefine

### ISSUE THREAD

**Issue by RP-Bioinfo** [BioinfoMachineLearning/ATOMRefine#5]
Hi, I followed all installation instructions for ATOMRefine but when I try to launch the example prediction I get the following error:

$ sh refine.sh example/T1062.pdb T1062 35 output
Using backend: pytorch
Traceback (most recent call last):
  File "/home/rpracella/ATOMRefine/predict.py", line 21, in <module>
    from amber import relax
  File "/home/rpracella/ATOMRefine/amber/relax.py", line 18, in <module>
    from amber import amber_minimize
  File "/home/rpracella/ATOMRefine/amber/amber_minimize.py", line 29, in <module>
    import jax
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/jax/__init__.py", line 63, in <module>
    from jax._src.api import (
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/jax/_src/api.py", line 48, in <module>
    from jax._src import callback as jcb
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/jax/_src/callback.py", line 26, in <module>
    from jax._src import dispatch
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/jax/_src/dispatch.py", line 58, in <module>
    from etils import epath
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/etils/epath/__init__.py", line 19, in <module>
    from etils.epath import testing
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/etils/epath/testing.py", line 27, in <module>
    from etils.epath import gpath
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/etils/epath/gpath.py", line 61, in <module>
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'

Best Regards,

Riccardo Pracella

**Comment by ZhiYeG** [comment]
Hi
This may caused by the conflict of Jax version, could you kindly tell me what Jax you use now?

**Comment by RP-Bioinfo** [comment]
I use jax 0.3.23

**Comment by ZhiYeG** [comment]
please try to update jax to jax==0.4.13 and jaxlib==0.4.13

**Comment by RP-Bioinfo** [comment]
Ok this solution solved the previous issue, but now the command gives me another error message:

$ sh refine.sh example/T1062.pdb T1062 35 output
Traceback (most recent call last):
  File "/home/rpracella/ATOMRefine/predict.py", line 14, in <module>
    from network2 import SE3Refine
  File "/home/rpracella/ATOMRefine/network2.py", line 8, in <module>
    import dgl
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/dgl/backend/__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/dgl/backend/__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/dgl/_ffi/base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/dgl/_ffi/base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by ZhiYeG** [comment]
Hi, these is cause by you environment setup. You should check your the CUDA driver version you used and install the relevant PyTorch version. Also you may need to make sure you have the GPU environment

**Comment by RP-Bioinfo** [comment]
Ok I fixed my CUDA environment but now It seems that my numpy is too much upgraded. I have this error:
$ sh refine.sh example/T1062.pdb T1062 35 output
Using backend: pytorch
Traceback (most recent call last):
  File "/home/rpracella/ATOMRefine/predict.py", line 20, in <module>
    from amber import protein
  File "/home/rpracella/ATOMRefine/amber/protein.py", line 19, in <module>
    from amber import residue_constants
  File "/home/rpracella/ATOMRefine/amber/residue_constants.py", line 576, in <module>
    restype_atom37_to_rigid_group = np.zeros([21, 37], dtype=np.int)
  File "/home/rpracella/anaconda3/envs/ATOMRefine/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The problem is that my conda don't allow me to downgrade numpy for conflicts with versions of other packages. How Can I fix it? Thanks in advance

Best Regards,

Riccardo

**Comment by bernym12** [comment]
For me personally, I just went in and modified all instances of `np.int` to `int` in  `/home/rpracella/ATOMRefine/amber/residue_constants.py.` It's rather simple and not a breaking change as I've been running ATOMRefine with no issue in regards to this. There may be similar instances of this that crop up so just perform the same change to the mentioned files and then you should be good to go.
