### ISSUE TITLE
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'

### ISSUE THREAD

**Issue by EsToHi** [BioinfoMachineLearning/ATOMRefine#7]
Hi there,

Thank you first for this interesting package .. 
I have the following issue after installation :

(ATOMRefine) hicham@omega-Lambda-Vector:/data/sharedData/ATOMRefine$ sh refine.sh example/T1062.pdb T1062 35 output                                                                                             
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.                              
Traceback (most recent call last):
  File "/data/sharedData/ATOMRefine/predict.py", line 21, in <module>
    from amber import relax
  File "/data/sharedData/ATOMRefine/amber/relax.py", line 18, in <module>
    from amber import amber_minimize
  File "/data/sharedData/ATOMRefine/amber/amber_minimize.py", line 28, in <module>
    from amber import utils
  File "/data/sharedData/ATOMRefine/amber/utils.py", line 21, in <module>
    from simtk.openmm.app.internal.pdbstructure import PdbStructure
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'
(ATOMRefine) hicham@omega-Lambda-Vector:/data/sharedData/ATOMRefine$

**Comment by EsToHi** [comment]
Solved.
Just modify predict.py, relax.py, amber_minimize.py, and utils.py from simtk to only openmm.
Check this issue for details:
https://github.com/google-deepmind/alphafold/commit/955737f12cc4b27398fe2369417fc2cc79815eb6
